const products = [
  {
    _id: "123241",
    name: "Hyperice | Hypervolt Percussive Massage Device Featuring Quite Glide Technology",
    price: 299.99,
    brand: '',
    image: "https://hyperice.com/media/wysiwyg/HV_Render.png",
    description: "",
    category: '',
    inStockCounter: 3,
    rating: 5,
    reviewsNum: 1,
  },
  {
    _id: "123241",
    name: "Hyperice | Hypervolt Percussive Massage Device Featuring Quite Glide Technology",
    price: 299.99,
    brand: '',
    image: "https://hyperice.com/media/wysiwyg/HV_Render.png",
    description: "",
    category: '',
    inStockCounter: 3,
    rating: 5,
    reviewsNum: 1,
  },
  {
    _id: "123241",
    name: "Hyperice | Hypervolt Percussive Massage Device Featuring Quite Glide Technology",
    price: 299.99,
    brand: '',
    image: "https://hyperice.com/media/wysiwyg/HV_Render.png",
    description: "",
    category: '',
    inStockCounter: 3,
    rating: 5,
    reviewsNum: 1,
  },
  {
    _id: "123241",
    name: "Hyperice | Hypervolt Percussive Massage Device Featuring Quite Glide Technology",
    price: 299.99,
    brand: '',
    image: "https://hyperice.com/media/wysiwyg/HV_Render.png",
    description: "",
    category: '',
    inStockCounter: 3,
    rating: 5,
    reviewsNum: 1,
  },
  {
    _id: "123241",
    name: "Hyperice | Hypervolt Percussive Massage Device Featuring Quite Glide Technology",
    price: 299.99,
    brand: '',
    image: "https://hyperice.com/media/wysiwyg/HV_Render.png",
    description: "",
    category: '',
    inStockCounter: 3,
    rating: 5,
    reviewsNum: 1,
  },
];

export default products;