const products = [
  {
    _id: "1",
    name: "Hyperice | Hypervolt Percussive Massage Device Featuring Quite Glide Technology",
    price: 299.99,
    brand: 'Hyperice',
    image: "https://hyperice.com/media/wysiwyg/HV_Render.png",
    description: "Nice massage device",
    category: 'Electronics',
    inStockCounter: 3,
    rating: 5,
    reviewsNum: 1,
  },
  {
    _id: "2",
    name: "Bose - Sleepbuds II — Soothing Sounds and Noise-masking Technology Designed for Better Sleep - White/Silve",
    price: 248.99,
    brand: 'Bose',
    image: "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6425/6425583_sd.jpg;maxHeight=640;maxWidth=550",
    description: "Some nice sounding headphones",
    category: 'Electronics',
    inStockCounter: 13,
    rating: 4,
    reviewsNum: 3,
  },
  {
    _id: "3",
    name: "Braun - 6-in-1 Trimmer MGK3221 - Volt Green",
    price: 26.99,
    brand: 'Braun',
    image: "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6415/6415811_rd.jpg;maxHeight=640;maxWidth=550",
    description: "A nice shaver",
    category: 'Health',
    inStockCounter: 4,
    rating: 5,
    reviewsNum: 10,
  },
  {
    _id: "4",
    name: "Swagtron - Swagskate Electric Skateboard w/ 6 mi Max Operating Range & 9.3 mph Max Speed - Black",
    price: 105.99,
    brand: 'Swagtron',
    image: "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6410/6410615_sd.jpg;maxHeight=640;maxWidth=550",
    description: "A sweet new skateboard for a sweet new ride",
    category: 'Electronics',
    inStockCounter: 5,
    rating: 3,
    reviewsNum: 8,
  },
  {
    _id: "5",
    name: 'Samsung - CHG9 Series C49HG90DMN 49" HDR LED Curved FHD FreeSync Monitor - Matte dark blue black',
    price: 899.99,
    brand: 'Samsung',
    image: "httpshttps://pisces.bbystatic.com/image2/BestBuy_US/images/products/6115/6115611_sd.jpg;maxHeight=640;maxWidth=550://hyperice.com/media/wysiwyg/HV_Render.png",
    description: "A beautiful 4k Monitor",
    category: 'Electronics',
    inStockCounter: 1,
    rating: 5,
    reviewsNum: 100,
  },
];

export default products;